### ISSUE TITLE
Production Marcom loader

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#881]
Matt reported this morning that he couldn't upload files using the Marketing loader. This is the screenshot he sent me of the stalled load:

![screen shot 2016-01-04 at 11 54 05 am 2 copy jpg](https://cloud.githubusercontent.com/assets/4663073/12096037/8d7bccb4-b2e0-11e5-8c88-2925c7556713.jpeg)

I tried to upload the files in staging, which worked, so I decided to upload the files for him in production. I tried first as him, then as myself, but both times the load stalled. I can't upload the files individually, either (those uploads stall, too). 

I don't see anything in FITS that tells me there's anything wrong with the files themselves, and they do upload just fine in staging, so I'm not sure that the files are the issue here. But, I've tried uploading other files in production, individually and with the loaders, which works.

**Comment by dgcliff** [comment]
Hm...ok. Will look into it.

**Comment by dgcliff** [comment]
I was able to reproduce what you saw, but was also able to upload shortly thereafter. Best as I can diagnose, this appears to be an ITS related networking problem (nb4676 wasn't reachable during the upload process).

Could you try again, and let me know if it works or not?

**Comment by sarahjeansweeney** [comment]
I tried again, same result.

**Comment by dgcliff** [comment]
*shrug* I was able to upload one of the images just fine - https://repository.library.northeastern.edu/files/neu:cj82k731z

We can try to replicate on your laptop at the meeting I suppose

**Comment by dgcliff** [comment]
Fixed - it was Ernesto's security updates to Apache killing the upload

http://forums.b2evolution.net/fix-for-server-error-500-on-uploading-images - solution found here. Will email Ernesto/Karl to not touch that file, and that the change was deliberate.

**Comment by sarahjeansweeney** [comment]
Okay - I tried again this morning as Matt, but still no luck. Same stalled page behavior, but a different message this time: "Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)"

![2016-01-05_0905](https://cloud.githubusercontent.com/assets/4663073/12117008/c58492b6-b38b-11e5-8ab2-891b5193949d.png)

**Comment by sarahjeansweeney** [comment]
I should also mention I tried to load a new set of files he sent me yesterday, which is approximately 18MB.

**Comment by dgcliff** [comment]
Also related to the security measures put in place. Will probably comment out the whole thing at this point. Playing skeetshoot with untested measures is not a reliable way forward.

**Comment by dgcliff** [comment]
I've done that - @sarahjeansweeney if you could try again, and let me know

**Comment by sarahjeansweeney** [comment]
It worked! The files loaded successfully :)

**Comment by dgcliff** [comment]
Ok - let's put a pin in this (the new security measures) until we can find some time to test it out on staging.
